---
title: "Capstone EDA"
author: "Jared Allen"
date: "30/09/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(tidytext)
library(quanteda)
```

## Data Import

Data import has been accomplished through the use of the readLines function in R, storing the data in tibble format to adhere to tidy data principles.

```{r data_import, warning=FALSE, echo=TRUE}

con<- file("Data/final/en_US/en_US.twitter.txt","r")
en_us_twitter <- readLines(con)
en_us_twitter <- tibble(en_us_twitter)
close(con)

con<- file("Data/final/en_US/en_US.blogs.txt","r")
en_us_blogs <- readLines(con)
en_us_blogs <- tibble(en_us_blogs)
close(con)

con<- file("Data/final/en_US/en_US.news.txt","r")
en_us_news <- readLines(con)
en_us_news <- tibble(en_us_news)
close(con)
```

```{r data_summary}
summary(en_us_twitter)
summary(en_us_blogs)
summary(en_us_news)

```

```{r restructure_trigrams}

en_us_twitter_tidy_trigrams <-
  en_us_twitter %>%
  unnest_tokens(trigram,en_us_twitter,token = "ngrams",n=3)

```

```{r counts}

en_us_twitter_tidy_trigrams %>%
  count(trigram,sort=TRUE)

```

## EDA
```{r quanteda test}
library(readtext)
QE_en_us_twitter <- corpus(readtext("Data/final/en_US/en_US.twitter.txt"))
QE_en_us_blogs <- corpus(readtext("Data/final/en_US/en_US.blogs.txt"))
QE_en_us_news <- corpus(readtext("Data/final/en_US/en_US.news.txt"))

QE_all <- QE_en_us_twitter + QE_en_us_blogs + QE_en_us_news
```

```{r tokenize}

qedadfm <- dfm(QE_all)

textplot_wordcloud(qedadfm)

```